version: "3.8"
services:
  client:
    build: ./client
    container_name: client
    ports:
      - "3000:3000"
    stdin_open: true
    tty: true
    volumes:
      - /app/node_modules
      - ./client:/app

